version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: mysql
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin12345
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql